baseURL = '/'
languageCode = 'en-us'
title = 'Even Falkenberg Langås'
theme = 'typo'

[taxonomies]
tag = 'tags'

googleAnalytics = "G-R6VE55D8WD"

[params]

# Meta description
description = "A Tech Blog"

# Appearance settings
theme = 'auto'

# homePicture = "./profilbilde.jpg"
homePicture = "./portfoliopagepicture.png"
currentPosition = "Head of R&D at Twilligent / PhD Research Fellow at UiA"

aboutMeAudio = "./phdpodcast.wav"
aboutMeVideo = "https://www.youtube.com/embed/xSnyjV5pLr4"

# Intro on main page, content is markdown
homeIntroTitle = 'Mechatronics Software Engineer'
homeIntroContent = """
I am a dedicated and creative mechatronics engineer with a Master's degree from the University of Agder. My experience with R&D in addition to building a startup makes me a versatile asset. I like a challenge and love to learn new things!
"""

# Collection to display on home
homeCollectionTitle = 'Projects'
homeCollection = 'projects'

# Lists parameters
paginationSize = 10
listSummaries = true
listDateFormat = '2 Jan 2006'

# Breadcrumbs
breadcrumbs = false

# Social icons

[[params.social]]
name = "email"
url = "mailto:evenf.langas@gmail.com"

[[params.social]]
name = "linkedin"
url = "https://www.linkedin.com/in/evenlangas/"

[[params.social]]
name = "github"
url = "https://github.com/evenlangas"

[[params.social]]
name = "discord"
url = "https://discord.com/users/evenlangas"

[[params.social]]
name = "googlescholar"
url = "https://scholar.google.com/citations?user=lzgwLVgAAAAJ&hl=en"

# Main menu pages
[[params.menu]]
name = "home"
url = "/"

[[params.menu]]
name = "projects"
url = "/projects"

[[params.menu]]
name = "publications"
url = "/publications"

[[params.menu]]
name = "cv"
url = "/cv"

# Syntax highligth on code blocks
[markup]
[markup.highlight]
style = 'algol'

# Giscus comments
[params.giscus]
enable = false
repo = "user/repo"
repoid = "repoId"
category = "General"
categoryid = "categoryId"
mapping = "pathname"
theme = "preferred_color_scheme"