baseURL = '/'
languageCode = 'en-us'
title = 'Even Falkenberg Langås'
theme = 'typo'

[taxonomies]
tag = 'tags'

# Google analytics code
googleAnalytics = "G-xxxxxxxxx"

[params]
# Meta description
description = "A Tech Blog"

# Appearance settings
theme = 'auto'

# Intro on main page, content is markdown
homeIntroTitle = 'Hi!'
homeIntroContent = """
I am a dedicated and creative mechatronics engineer with a Master's degree from the University of Agder. My experience with R&D in addition to building a startup makes me a versatile asset. I like a challenge and love to learn new things!"""


# Collection to display on home
homeCollectionTitle = 'Posts'
homeCollection = 'posts'

# Lists parameters
paginationSize = 100
listSummaries = true
listDateFormat = '2 Jan 2006'

# Breadcrumbs
breadcrumbs = true

# Social icons


[[params.social]]
name = "email"
url = "mailto:evenf.langas@gmail.com"

[[params.social]]
name = "linkedin"
url = "https://www.linkedin.com/in/evenlangas/"

[[params.social]]
name = "github"
url = "https://github.com/evenlangas"

[[params.social]]
name = "discord"
url = "https://discord.com/users/evenlangas"

[[params.social]]
name = "googlescholar"
url = "https://scholar.google.com/citations?user=lzgwLVgAAAAJ&hl=en"

[[params.social]]
name = "researchgate"
url = "https://www.researchgate.net/profile/Even_Langas"

# Main menu pages
[[params.menu]]
name = "home"
url = "/"

[[params.menu]]
name = "posts"
url = "/posts"

[[params.menu]]
name = "about"
url = "/about"

# Syntax highligth on code blocks
[markup]
[markup.highlight]
style = 'algol'

# Giscus comments
[params.giscus]
enable = false
repo = "user/repo"
repoid = "repoId"
category = "General"
categoryid = "categoryId"
mapping = "pathname"
theme = "preferred_color_scheme"